### ISSUE TITLE
Orchestrate the deployment of statsd, OpenTSDB and Grafana

### ISSUE THREAD

**Issue by ruphy** [italia/daf-recipes#2]
Write a docker-compose which feeds the output of a custom test program to a custom infrastructure, built this way:
statsd as data receiver, OpenTSDB as storage, Grafana as visualizer.

The `docker-compose` should build the instance of statsd, OpenTSDB and Grafana and link them together accordingly, while the external, custom code, should not be in a docker container.

**Comment by jenkin** [comment]
@ruphy if resolved, please close this issue.

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed.
